### ISSUE TITLE
Conditionally close the dialog when escapable

### ISSUE THREAD

**Issue by azhiv** [zestia/ember-modal-dialog#11]
It would be very convenient if the dialog would close conditionally when the user attempts to close it. Consider the following scenario: if the user clicks outside of the dialog and it should close, we show another dialog asking "Are you sure?". If yes, close both dialogs. If not, close the "Are you sure?" dialog and keep the original one open.
I was able to achieve the desired result by overriding `_hide` method:
```ts
_hide() {
  if (!this.args.onClosing || this.args.onClosing() === true) {
    return super._hide();
  }

  return reject();
}
```
But since your last changes this no longer works.

**Comment by azhiv** [comment]
One problem - the main dialog "blinks" (fades-out) when clicking outside of the dialog, then instantly appears.

https://user-images.githubusercontent.com/32125472/136770140-b217dcfc-7f3f-4779-81b3-0b3fdd7c1c9f.mov

**Comment by azhiv** [comment]
Well, it's more of how we already implemented our callbacks. Sometimes we return true/false, but may also perform ember concurrency tasks when escaping the dialog. In this case we don't care about the result (true/false), but your implementation casts a task instance to true.

**Comment by azhiv** [comment]
> I'll make that change.
It works great now! Looking forward for the release.

**Comment by amk221** [comment]
Thanks, can you elaborate on how you're wiring up `onEscape` in such a way
that would lead to your requirement of `escapeable === true`? If you were
using an EC task, it should still work without that? 🤔

**Comment by amk221** [comment]
Does this demo have what you need: https://zestia.github.io/ember-modal-dialog/
