### ISSUE TITLE
When escapable, mouseUp outside of the dialog closes it

### ISSUE THREAD

**Issue by azhiv** [zestia/ember-modal-dialog#5]
In your demo, if you select text spreading the cursor out of the dialog and release the mouse button, the dialog closes. This is not desired in most cases, is it?

Is there a way to prevent such behaviour?

**Comment by amk221** [comment]
Are you sure it does that? I can't replicate it. Can you do a screen recording perpahs?

**Comment by amk221** [comment]
Ah, I just re-created it. Let me investigate...

**Comment by amk221** [comment]
Yeh, that seems expected to me, the user can click outside the modal, to close it

**Comment by amk221** [comment]
It's been that way since the addons inception, it's this line:
https://github.com/zestia/ember-modal-dialog/blob/main/addon/components/modal-dialog/index.js#L106

I think perhaps the confusion comes from escapable having a double meaning in this case.

Hmmm

**Comment by amk221** [comment]
I wonder what the impact would be if we removed that line.

**Comment by azhiv** [comment]
> Escapaple: the user can press escape to escape it
> Escapable: the user can click outside the box to escape it
I don't mind to have both of these. I consider clicking outside of the window to be very handy (instead of looking for the Cancel (or whatever) button that closes the window). You see, the thing that annoys me is that the dialog closes when I perform mouseDown inside and mouseUp outside.

I was wondering if the latter may be workarounded/fixed somehow, i.e. your component would ignore mouseUp and wouldn't treat it like a click outside. Frankly speaking I don't think there's an easy way to achieve this. I compared two events in the `handleClick` for the two testcases (mouseUp inside/outside, mouseUp outside) and they don't seem to differ. I assume this would require some extra logic to handle this.

**Comment by amk221** [comment]
Gotcha, let me see.

**Comment by amk221** [comment]
Fix in 2.3.2

It raises the point, that the component could do with a small refactoring, to make the modal dialog be the actual box itself. And, any sort of backdrop could just be a pseudo element. Will do that another day.

**Comment by azhiv** [comment]
Amazing speed!

**Comment by amk221** [comment]
No problem, thanks for raising.

I've just updated the demo size, ty.
