### ISSUE TITLE
Don't focus the first element after the window gets focus

### ISSUE THREAD

**Issue by azhiv** [zestia/ember-modal-dialog#9]
So you have a special piece of code that focuses the first focusable element when the window gets focus. This behaviour is not consistent with the case of the initial dialog opening:
In one of the dialogs of our app the first focusable element is ember-power-element  trigger. So on the initial dialog open the form is neat, but if I change the browser tab and then change it back, the power calendar gets opened which is not desired. This happens because the focus on the trigger does this.

The best workaround I managed to find is overriding `_handleFocusedWindow() {}`, which is kinda ugly. Do you consider this feature to be absolutely necessary?

**Comment by amk221** [comment]
Apologies, I added that to satisfy  https://github.com/zestia/ember-modal-dialog/issues/7

It obviously needs more thought!

Let me get back to you

**Comment by amk221** [comment]
Hi, can you try this PR out: https://github.com/zestia/ember-modal-dialog/pull/10

**Comment by amk221** [comment]
Sorry, I was suggesting checking out the repo itself, I've not published any code yet.

Steps would be:

1. Clone repo
2. cd into it, run `npm i` `npm link`
3. cd into your app run `npm link @zestia/ember-modal-dialog`
4. run your app

**Comment by azhiv** [comment]
What I was trying to do is patching my `package.json` like so:
`"@zestia/ember-modal-dialog": "@zestia/ember-modal-dialog#_3.3.1",`
This is usually enough to point to a specific version of an addon. I'll try it your way though.

**Comment by amk221** [comment]
Ok thanks for baring with me

**Comment by azhiv** [comment]
This is what I get:
```
 ~/src/ember-modal-dialog   _3.3.1  npm i
...
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@zestia/animation-utils/-/animation-utils-3.0.0.tgz
npm ERR! 404
npm ERR! 404  '@zestia/animation-utils@3.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'ember-modal-dialog'
```

**Comment by azhiv** [comment]
Should I also pull this addon and `npm link` it?

**Comment by azhiv** [comment]
I succeeded building your branch!
The input is not focused after I switch the tabs. However, is it supposed to keep the focus if the element had focus before the tab switching? Not a big deal, but it is something I would expect.
https://user-images.githubusercontent.com/32125472/136362718-ffeeab4b-e652-4543-bd14-baef9d6ce7d6.mov

**Comment by amk221** [comment]
Released 3.3.2

**Comment by amk221** [comment]
Try now please!

**Comment by amk221** [comment]
Done
